// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGVHWBncfst16Ua6vmDiMQbxqEwuO83MA',
    appId: '1:489581687955:web:5bb0626226680246834966',
    messagingSenderId: '489581687955',
    projectId: 'sarisiteauthproject',
    authDomain: 'sarisiteauthproject.firebaseapp.com',
    storageBucket: 'sarisiteauthproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW7r4QPbCenF30axUilME3kbqpez8nV40',
    appId: '1:489581687955:android:a3eed6b57e81f38d834966',
    messagingSenderId: '489581687955',
    projectId: 'sarisiteauthproject',
    storageBucket: 'sarisiteauthproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPOzGwsd4V_7YifDUdvJODyipS8VIBd1c',
    appId: '1:489581687955:ios:c1b11d3140452fd2834966',
    messagingSenderId: '489581687955',
    projectId: 'sarisiteauthproject',
    storageBucket: 'sarisiteauthproject.firebasestorage.app',
    iosBundleId: 'com.example.sarisitefolder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPOzGwsd4V_7YifDUdvJODyipS8VIBd1c',
    appId: '1:489581687955:ios:c1b11d3140452fd2834966',
    messagingSenderId: '489581687955',
    projectId: 'sarisiteauthproject',
    storageBucket: 'sarisiteauthproject.firebasestorage.app',
    iosBundleId: 'com.example.sarisitefolder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGVHWBncfst16Ua6vmDiMQbxqEwuO83MA',
    appId: '1:489581687955:web:cdb36337a615ff89834966',
    messagingSenderId: '489581687955',
    projectId: 'sarisiteauthproject',
    authDomain: 'sarisiteauthproject.firebaseapp.com',
    storageBucket: 'sarisiteauthproject.firebasestorage.app',
  );
}
